// Stable public API — delegates to the intelligence engine.
export {
  calculateScore,
  averageRating,
  getStrongestArea,
  getMostUrgentArea,
  getLowestArea,
  getInsight,
  dimensionLabel,
  buildCurrentState,
  getTopThreePriorities,
  buildTwinInsights,
  buildNextAction,
  buildFutureHorizons,
  buildFutureScenarios,
  buildRiskRadar,
  getDimensionSummary,
  getPrimaryObstacle,
  getObstacleSummary,
} from "./intelligenceEngine";
